### PR TITLE
feat: Add resizeable panels

### PR DESCRIPTION
**Pull request by amareshsm**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?
Added resizable split-view to the resize editor and preview panel.

### CODE REVIEW

**Comment by nzakas** [comment]
I'm not sure we need this. As soon as you add resizable panels, you also need a way to reset to the default. I'm not sure it's worth the effort.

**Comment by amareshsm** [comment]
> I'm not sure we need this. As soon as you add resizable panels, you also need a way to reset to the default. I'm not sure it's worth the effort.

It’s similar to the behavior in the [[playground](https://eslint.org/play/)](https://eslint.org/play/), where the view resets when the page is reloaded. I think this would be particularly useful on smaller laptops, especially when focusing on either the code on the left or the preview on the right. This feature would allow us to expand the view as needed, providing more flexibility.

I'm open to other suggestions as well. If it seems unnecessary, we can close this.

**Comment by nzakas** [comment]
It looks like the resizing resets when the page is reloaded? If that's intended, then I'm okay with it.

**Comment by amareshsm** [comment]
> It looks like the resizing resets when the page is reloaded? If that's intended, then I'm okay with it.

ya, it resets when reloaded.

**Review by nzakas — APPROVED** [review]
LGTM.

**Pull request merged**
